/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container-lowest": "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "tertiary-fixed-dim": "#a0cfd5",
        "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
        "on-secondary-fixed-variant": "#2f4b4f",
        "secondary": "rgb(var(--color-secondary) / <alpha-value>)",
        "inverse-primary": "#3c656a",
        "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
        "inverse-on-surface": "#14353a",
        "on-tertiary-container": "#3a676d",
        "surface-container-high": "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "on-tertiary": "#00363c",
        "error-container": "rgb(var(--color-error-container) / <alpha-value>)",
        "on-primary-fixed-variant": "#234d52",
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-error-container": "rgb(var(--color-on-error-container) / <alpha-value>)",
        "on-tertiary-fixed": "#001f23",
        "on-secondary": "rgb(var(--color-on-secondary) / <alpha-value>)",
        "tertiary": "#e7fcff",
        "secondary-container": "#314e51",
        "surface-dim": "rgb(var(--color-surface-dim) / <alpha-value>)",
        "background": "rgb(var(--color-background) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--color-primary-fixed-dim) / <alpha-value>)",
        "surface-bright": "#1d3e43",
        "on-primary-container": "rgb(var(--color-on-primary-container) / <alpha-value>)",
        "on-error": "rgb(var(--color-on-error) / <alpha-value>)",
        "on-background": "rgb(var(--color-on-background) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--color-secondary-fixed-dim) / <alpha-value>)",
        "primary-container": "rgb(var(--color-primary-container) / <alpha-value>)",
        "surface-tint": "rgb(var(--color-primary-fixed-dim) / <alpha-value>)",
        "tertiary-container": "#b5e4eb",
        "surface-container-low": "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "error": "rgb(var(--color-error) / <alpha-value>)",
        "on-tertiary-fixed-variant": "#1e4d53",
        "surface": "rgb(var(--color-surface) / <alpha-value>)",
        "primary-fixed": "rgb(var(--color-primary-fixed) / <alpha-value>)",
        "primary": "rgb(var(--color-primary) / <alpha-value>)",
        "on-secondary-fixed": "#001f23",
        "surface-variant": "rgb(var(--color-surface-variant) / <alpha-value>)",
        "on-secondary-container": "#a0bec2",
        "inverse-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "secondary-fixed": "#c9e8ec",
        "surface-container": "rgb(var(--color-surface-container) / <alpha-value>)",
        "outline": "rgb(var(--color-outline) / <alpha-value>)",
        "on-primary-fixed": "#001f23",
        "tertiary-fixed": "#bcebf1"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "lg": "40px",
        "xl": "64px",
        "margin-desktop": "32px",
        "max-width": "1440px",
        "xs": "4px",
        "md": "24px",
        "margin-mobile": "16px",
        "gutter": "16px",
        "base": "8px",
        "sm": "12px"
      },
      "fontFamily": {
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "code-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "label-lg": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "code-sm": ["13px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-lg": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
