/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container-lowest": "#001114",
        "tertiary-fixed-dim": "#a0cfd5",
        "on-primary": "#05363b",
        "on-secondary-fixed-variant": "#2f4b4f",
        "secondary": "#aeccd0",
        "inverse-primary": "#3c656a",
        "outline-variant": "#414849",
        "inverse-on-surface": "#14353a",
        "on-tertiary-container": "#3a676d",
        "surface-container-highest": "#19393e",
        "on-tertiary": "#00363c",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#234d52",
        "on-surface": "#c6e9ef",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#001f23",
        "on-secondary": "#183538",
        "tertiary": "#e7fcff",
        "secondary-container": "#314e51",
        "surface-dim": "#00161a",
        "background": "#00161a",
        "primary-fixed-dim": "#a3ced4",
        "surface-bright": "#1d3e43",
        "on-primary-container": "#3d666c",
        "on-error": "#690005",
        "on-background": "#c6e9ef",
        "on-surface-variant": "#c0c8c9",
        "surface-container-high": "#0c2e33",
        "secondary-fixed-dim": "#aeccd0",
        "primary-container": "#b8e3e9",
        "surface-tint": "#a3ced4",
        "tertiary-container": "#b5e4eb",
        "surface-container-low": "#001f24",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#1e4d53",
        "surface": "#00161a",
        "primary-fixed": "#bfeaf0",
        "primary": "#e6fcff",
        "on-secondary-fixed": "#001f23",
        "surface-variant": "#19393e",
        "on-secondary-container": "#a0bec2",
        "inverse-surface": "#c6e9ef",
        "secondary-fixed": "#c9e8ec",
        "surface-container": "#002429",
        "outline": "#8a9293",
        "on-primary-fixed": "#001f23",
        "tertiary-fixed": "#bcebf1"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "lg": "40px",
        "xl": "64px",
        "margin-desktop": "32px",
        "max-width": "1440px",
        "xs": "4px",
        "md": "24px",
        "margin-mobile": "16px",
        "gutter": "16px",
        "base": "8px",
        "sm": "12px"
      },
      "fontFamily": {
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "code-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "label-lg": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "code-sm": ["13px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-lg": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
